ヒントをください
sanuki0679/learning_plan pull request #1
Opened 2023-02-15 05:38 UTC by sanuki0679

### 未達成の学習内容を完了させることができません。completion_date に完了日を入力することができません。

2023-02-15 06:36 UTC, kzri4 commented on functions.php
> +        date_format(completion_date, '%Y%m%d') = :status
以下のように修正するとどうでしょうか？
```  
  $sql = <<<EOM
    UPDATE
        plans
    SET
        completion_date = :status
    WHERE
        id = :id
    EOM;
```

2023-02-15 06:36 UTC, kzri4 commented on done.php
> +$status = filter_input(INPUT_GET, 'status');
$status = filter_input(INPUT_GET, 'status');　
は、status自体はindex.phpから何も渡って来ず、done.phpで変数にdate関数で格納しているので不要です👍

2023-02-19 07:03 UTC, zeeero4 commented on index.php
> +    </div>
` <?php foreach ($notyet_plans as $plan) : ?>`
より下以降の部分がインデントの位置がおかしかったりするので、整理をお願いします！
原因としては閉じタグに誤りがあったりするので、それが影響してそうですので、確認お願いします。

2023-02-19 07:03 UTC, zeeero4 commented on index.php
> +    <th class="plan-due-date"><?= h(date('Y/m/d', strtotime($plan['due_date']))) ?></td>
ここも閉じタグに誤りがありそうです！

2023-02-19 07:03 UTC, zeeero4 commented on functions.php
> +
未完了のものは、期限日を昇順でデータ表示できるようにお願いします！

2023-02-19 07:03 UTC, zeeero4 commented on functions.php
> +}
完了済みのものは、完了日を降順でデータ表示できるようにお願いします！

2023-02-19 07:03 UTC, zeeero4 commented on functions.php
> +
日付が入力されていない時のエラー文表示をお願いします！

2023-02-19 07:03 UTC, kzri4 commented on done.php
> +$status = date("Ymd");
変数が何を表しているかすぐにわかりにくいので、`$comp_date`とかの方がいいかと思います！

2023-02-19 07:03 UTC, kzri4 commented on done_cancel.php
> +$status = NULL;
ここも同様です！

2023-02-21 07:41 UTC, kzri4 commented on functions.php
> +
今のままだと、日付と内容双方とも内容を変更しないと更新がかからないので、片方だけ(学習内容のみor 期限日)変更しても更新がかかるようにしてみてください！

2023-02-21 07:41 UTC, kzri4 commented on index.php
> +                </ul><?php endif; ?>
タグの位置がずれて、分かりにくくなっていますね！
以下のような形がいいと思います！
```
<?php if ($errors) : ?>
    <ul class="errors">
        <?php foreach ($errors as $error) : ?>
            <li><?= h($error) ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
```

2023-02-21 07:41 UTC, kzri4 commented on index.php
> +                </tbody>
tbody以下は以下のように整える方が見やすいかと思います！
```
<tbody>
    <!-- 未完了のデータを表示 -->
    <?php foreach ($notyet_plans as $plan) : ?>
        <tr>
            <th class="plan-title">
                <?= h($plan['title']) ?>
            </th>
            <!-- 期限切れだったら赤く表示する ためのif文 -->
            <?php if (strtotime('now') >= strtotime($plan['due_date'])) : ?>
            <th class="expired">
                <?= h(date('Y/m/d', strtotime($plan['due_date']))) ?>
            </th>
            <?php else : ?>
            <th class="plan-due-date">
                <?= h(date('Y/m/d', strtotime($plan['due_date']))) ?>
            </th>
            <?php endif; ?>
            <!-- done.php へのURLを追記 -->
            <th class="done-link-area">
                <a href="done.php?id=<?= h($plan['id']) ?>">完了</a>
            </th><!-- edit.php へのURLを追記 -->
            <th class="edit-link-area">
                <a href="edit.php?id=<?= h($plan['id']) ?>">編集</a>
            </th><!-- delete.php へのURLを追記 -->
            <th class="delete-link-area">
                <a href="delete.php?id=<?= h($plan['id']) ?>">削除</a>
            </th>
        </tr>
    <?php endforeach; ?>
</tbody>
```

2023-02-21 07:45 UTC, kzri4 commented
https://github.com/sanuki0679/learning_plan/pull/1#discussion_r1111179436

https://github.com/sanuki0679/learning_plan/pull/1#discussion_r1111179553

2023-02-23 03:37 UTC, naoto1192 commented
編集で日付が未入力の場合、エラーが発生していますので、再度修正してみてください！
内容と日付、どちらかの一方でも変更できるようにお願いします😊

https://github.com/sanuki0679/learning_plan/pull/1#discussion_r1112664327

2023-02-23 03:45 UTC, naoto1192 requested changes
コメントしましたので、修正お願いします😊

2023-02-23 03:45 UTC, naoto1192 commented on style.css
> +
800px以下からボタンのレイアウトが崩れてしまうので、修正お願いします！
（これから対応予定でしたらすみません🙇‍♂️）

2023-02-25 04:47 UTC, naoto1192 requested changes
コメントしましたので、ご確認お願いします😊

2023-02-25 04:47 UTC, naoto1192 commented on functions.php
> +    }
どちらか一方を更新する場合は、以下のように変更してみてはいかがでしょうか😊
```
    if ($title == $plan['title'] &&
        $due_date == $plan['due_date']) {
        $errors[] = MSG_NO_CHANGE;
    }
```

2023-02-25 04:47 UTC, naoto1192 commented on style.css
> +
800px以下でも、ボタンの文字が横並びになるように対応してみてください😊

2023-02-26 04:02 UTC, kazu-taka requested changes
@sanuki0679 
あと少しなので頑張って下さい😊

2023-02-26 04:02 UTC, kazu-taka commented on style.css
> +    margin: 30px auto;
@sanuki0679 
白い余白が入ってしまっているので、.wapperのmarginは削除してOKです✨
<img width="998" alt="image" src="https://user-images.githubusercontent.com/5278718/221391532-4c165332-0b2f-4475-8a37-86862a181b9c.png">

2023-02-26 04:02 UTC, kazu-taka commented on style.css
> +    padding: 10px 50px 10px 50px;
@sanuki0679 
もう少し上下のpaddingの値を増やして上げたほうが良いと思います✨
また、上下の値は一緒、左右の値も一緒の場合は、`padding: 10px 50px`だけで、上下、左右の値を設定することが可能です😊
<img width="961" alt="image" src="https://user-images.githubusercontent.com/5278718/221391597-97e1bdaf-c6ee-4553-9cac-94daba037e8b.png">

2023-02-26 04:34 UTC, kazu-taka commented
@sanuki0679 
問題ないのでマージしてOKです😊
![LGTM](https://image.lgtmoon.dev/169038)

2023-02-26 05:12 UTC, merged